---
title: 'Schedule'
layout: page
---

We have 12 seminar sessions together.

The plan below is provisional. I am happy to adapt the topics, as well as the schedule, to the needs and interests of the students. Likely, we will change some topics and orderings as we go.

Two lectures will be held via Zoom as I will not be in Lucerne.

| Date                 | Topic                                                                                                                |
|------------------|------------------------------------------------------|
| 22 February 2024     | [Introduction + Where is the digital revolution?](lectures.html#week-1-introduction-where-is-the-digital-revolution) |
| 29 February 2024     | [Text as Data](lectures.html#week-2-text-as-data)                                                                    |
| 07 March 2024        | [Setting up your Development Environment](lectures.html#week-3-setting-up-your-development-environment)              |
| 14 March 2024        | [Introduction to the Command-line](lectures.html#week-4-introduction-to-the-command-line)                            |
| 21 March 2024        | [Basic NLP with Command-line](lectures.html#week-5-basic-nlp-with-command-line)                                      |
| 28 March 2024        | [Introduction to Python in VS Code](lectures.html#week-6-introduction-to-python-in-vs-code)                          |
| 04 April 2024        | *no lecture (Osterpause)*                                                                                            |
| 11 April 2024        | [Working with (your own) Data](lectures.html#week-7-working-with-data)                                               |
| 18 April 2024        | [Data Analysis of Swiss Media](lectures.html#week-8-data-analysis-of-swiss-media)                                    |
| 25 April 2024 (Zoom) | [Ethics and the Evolution of NLP](lectures.html#week-9-ethics-and-the-evolution-of-nlp)                              |
| 02 May 2024 (Zoom)   | [NLP with Python](lectures.html#week-10-nlp-with-python)                                                             |
| 09 May 2024          | no lecture (Christi Himmelfahrt)                                                                                     |
| 16 May 2024          | [NLP with Python II + Working Session](lectures.html#week-11-nlp-with-python-ii-working-session)                     |
| 23 May 2024          | [Mini-Project Presentations + Discussion](lectures.html#week-13-mini-project-presentations-discussion)               |
| 30 May 2024          | *no lecture (Fronleichnam)*                                                                                          |